# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5ea92796347b5f7aee27247de5cd701cc1311ad8198944cd32a521c1ad03073d8b3139aab8f6ec8bf38f66a00cdcaf5a8aa8222aed050c351f4e96f4de7557e

test:
  secret_key_base: 8cec5ef893723c7bd972c2e8d01e782cb581ea194f99cdad1f52d7183c96243c8bb0e70ef7c34b71e623c025728968f5878fb2264369e72e83adc2519cc35a89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
